//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qiang_Zhang_Assignment2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyTable
    {
        public int PId { get; set; }
        public string Suburb { get; set; }
        public string Location { get; set; }
        public int NumberofRooms { get; set; }
        public string PropertyType { get; set; }
        public int FloorArea { get; set; }
        public int LandArea { get; set; }
        public decimal RV { get; set; }
        public string Email { get; set; }
    }
}
